//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Presentacion
{


    public partial class FormTraducciones
    {

        protected global::System.Web.UI.WebControls.DropDownList ddlIdiomaEditar;

        protected global::System.Web.UI.WebControls.GridView gvTraducciones;

        protected global::System.Web.UI.WebControls.Button btnGuardarTraducciones;

        protected global::System.Web.UI.WebControls.Label lblMensaje;
    }
}
