//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Presentacion
{


    public partial class FormIdiomas
    {

        protected global::System.Web.UI.WebControls.TextBox txtCodigo;

        protected global::System.Web.UI.WebControls.TextBox txtNombre;

        protected global::System.Web.UI.WebControls.HiddenField hiddenIdIdioma;

        protected global::System.Web.UI.WebControls.Button btnAgregar;

        protected global::System.Web.UI.WebControls.Button btnEliminar;

        protected global::System.Web.UI.WebControls.Label lblMensaje;

        protected global::System.Web.UI.WebControls.GridView gvIdiomas;
    }
}
